name: Update NOTAMs

on:
  schedule:
    - cron: "0 1 * * *"   # every day at 01 am
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # to allow pushing changes
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - run: pip install requests beautifulsoup4
      - run: python scripts/scraper.py
      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add docs/notams.geojson
          git add history/*
          git commit -m "Update NOTAMs"
          git push
